<template>
    <div class="loadingio-spinner-eclipse-udqpovmo8s9">
        <div class="ldio-3aa5ly38m46">
            <div></div>
        </div>
    </div>
</template>

<script>
    export default {
        name: "SmallLoader"
    }
</script>

<style scoped>
    @keyframes ldio-3aa5ly38m46 {
        0% {
            transform: rotate(0deg)
        }
        50% {
            transform: rotate(180deg)
        }
        100% {
            transform: rotate(360deg)
        }
    }

    .ldio-3aa5ly38m46 div {
        position: absolute;
        animation: ldio-3aa5ly38m46 1s linear infinite;
        width: 80px;
        height: 80px;
        top: 10px;
        left: 10px;
        border-radius: 50%;
        box-shadow: 0 2px 0 0 #ff6d1d;
        transform-origin: 40px 41px;
    }

    .loadingio-spinner-eclipse-udqpovmo8s9 {
        width: 70px;
        height: 70px;
        display: inline-block;
        overflow: hidden;
        background: none;
    }

    .ldio-3aa5ly38m46 {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.7);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }

    .ldio-3aa5ly38m46 div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>