# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    proxy:
        1:
            host: '144.172.97.6'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        2:
            host: '107.189.12.74'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        3:
            host: '185.196.191.108'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        4:
            host: '196.16.179.81'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        5:
            host: '104.249.7.227'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        6:
            host: '185.195.222.57'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        7:
            host: '185.205.196.22'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        8:
            host: '185.199.116.46'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        9:
            host: '67.227.120.67'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'
        10:
            host: '185.207.99.204'
            port: '3199'
            user: 'alexander_hong-e9rdh'
            password: 'T2g6KR8pVI'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
