# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    proxy:
        1:
            host: '178.212.35.126'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        2:
            host: '196.17.81.208'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        3:
            host: '144.172.81.213'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        4:
            host: '104.194.138.177'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        5:
            host: '186.179.4.231'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        6:
            host: '104.194.152.157'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        7:
            host: '185.196.190.81'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        8:
            host: '104.233.54.177'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        9:
            host: '67.227.124.233'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        10:
            host: '91.205.104.121'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        11:
            host: '144.172.85.132'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        12:
            host: '196.16.247.208'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        13:
            host: '144.172.110.106'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        14:
            host: '185.188.79.199'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        15:
            host: '104.194.135.162'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        16:
            host: '216.10.5.27'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        17:
            host: '181.177.71.125'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        18:
            host: '107.189.14.97'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        19:
            host: '216.10.1.16'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        20:
            host: '216.10.6.249'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        21:
            host: '67.227.122.182'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        22:
            host: '196.16.169.255'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        23:
            host: '104.233.48.210'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        24:
            host: '186.179.25.115'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        25:
            host: '144.172.97.109'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        26:
            host: '144.172.94.35'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        27:
            host: '196.19.191.30'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        28:
            host: '107.189.25.125'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        29:
            host: '196.16.168.28'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'
        30:
            host: '104.233.55.25'
            port: '3199'
            user: 'alex_oles-drzwl'
            password: 'k6qpH4Ilxj'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
