parameters:
  proxy:
    1:
      host: '196.17.81.88'
      port: '3199'
      user: 'alex_oles-9ufj3'
      password: '03VizRhPeT'
      2:
        host: '185.193.19.79'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      3:
        host: '91.205.105.173'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      4:
        host: '104.194.144.35'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      5:
        host: '104.144.8.190'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      6:
        host: '162.245.1.27'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      7:
        host: '194.61.31.227'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      8:
        host: '104.249.5.244'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      9:
        host: '107.189.14.53'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      10:
        host: '144.172.87.161'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      11:
        host: '104.194.137.158'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      12:
        host: '144.172.110.139'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      13:
        host: '195.7.4.205'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      14:
        host: '195.200.210.243'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      15:
        host: '196.19.174.97'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      16:
        host: '162.245.1.33'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      17:
        host: '144.172.110.72'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      18:
        host: '162.245.7.44'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      19:
        host: '144.172.109.207'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      20:
        host: '45.57.231.215'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      21:
        host: '104.249.1.143'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      22:
        host: '196.19.189.138'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      23:
        host: '104.194.133.81'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      24:
        host: '144.172.81.93'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      25:
        host: '144.172.107.218'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      26:
        host: '196.16.70.88'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      27:
        host: '144.172.103.83'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      28:
        host: '216.10.5.217'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      29:
        host: '181.177.68.133'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'
      30:
        host: '107.189.22.122'
        port: '3199'
        user: 'alex_oles-9ufj3'
        password: '03VizRhPeT'