parameters:
  proxy:
    11:
      host: '172.86.107.180'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    12:
      host: '104.194.146.22'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    13:
      host: '185.205.199.123'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    14:
      host: '185.193.73.64'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    15:
      host: '104.194.136.159'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    16:
      host: '107.189.22.82'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    17:
      host: '67.227.120.195'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    18:
      host: '196.17.89.184'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    19:
      host: '172.86.107.170'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    20:
      host: '107.189.17.236'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    21:
      host: '196.16.226.30'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    22:
      host: '104.233.52.82'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    23:
      host: '104.194.148.181'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    24:
      host: '144.172.108.186'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    25:
      host: '172.86.110.144'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    26:
      host: '185.199.116.30'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    27:
      host: '104.194.155.132'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    28:
      host: '104.194.152.233'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    29:
      host: '185.188.77.67'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    30:
      host: '196.18.246.126'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    31:
      host: '185.195.221.176'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    32:
      host: '185.205.198.204'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    33:
      host: '104.194.147.109'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    34:
      host: '196.16.176.40'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    35:
      host: '172.86.110.22'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    36:
      host: '107.189.20.140'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    37:
      host: '104.194.139.254'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    38:
      host: '185.205.198.174'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    39:
      host: '196.17.73.88'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    40:
      host: '144.172.99.210'
      port: '3199'
      user: 'alexander_hong-k4bur'
      password: 'TXSgbzOAEZ'
    41:
      host: '144.172.101.246'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    42:
      host: '196.17.91.120'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    43:
      host: '195.200.210.133'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    44:
      host: '144.172.102.195'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    45:
      host: '104.233.52.57'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    46:
      host: '196.16.222.75'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    47:
      host: '95.214.219.85'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    48:
      host: '104.194.140.176'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    49:
      host: '104.194.152.120'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    50:
      host: '196.18.248.131'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    51:
      host: '195.200.210.182'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    52:
      host: '107.189.17.142'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    53:
      host: '196.16.176.16'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    54:
      host: '185.199.119.81'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    55:
      host: '199.168.121.17'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    56:
      host: '196.16.69.247'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    57:
      host: '172.86.110.251'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    58:
      host: '67.227.123.254'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    59:
      host: '80.65.208.227'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    60:
      host: '185.195.212.17'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    61:
      host: '185.195.220.181'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    62:
      host: '196.16.222.226'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    63:
      host: '185.205.197.97'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    64:
      host: '185.188.76.33'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    65:
      host: '144.172.87.174'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    66:
      host: '162.245.4.147'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    67:
      host: '104.194.155.186'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    68:
      host: '185.195.213.180'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    69:
      host: '104.249.0.246'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'
    70:
      host: '196.17.89.80'
      port: '3199'
      user: 'alex_oles-xy2zy'
      password: 'cSZizfGqAo'